### ISSUE TITLE
NullPointerException on running Example.image.draw

### ISSUE THREAD

**Issue by kris48k** [underscoreio/creative-scala#37]
On a fresh clone of the project, the log looks like this:

```
scala> Example.image.draw
java.lang.NullPointerException
  at java.util.concurrent.ConcurrentLinkedQueue.checkNotNull(ConcurrentLinkedQueue.java:920)
  at java.util.concurrent.ConcurrentLinkedQueue.offer(ConcurrentLinkedQueue.java:327)
  at java.util.concurrent.ConcurrentLinkedQueue.add(ConcurrentLinkedQueue.java:297)
  at doodle.jvm.Java2DFrame.interpret(Java2DFrame.scala:19)
  at doodle.jvm.Java2DFrame.interpret(Java2DFrame.scala:8)
  at doodle.syntax.ImageSyntax$ToImageOps.draw(ImageSyntax.scala:9)
  ... 39 elided
```

P.S.: happens only through sbt console. On IntelliJ Idea the error is not reproduced.

**Comment by aaronlevin** [comment]
I'm also seeing this issue on linux. Strangely, if I install `sbt-assembly`, assemble a fat jar, and then run it via `java -jar ...` I don't get the exception.

**Comment by aaronlevin** [comment]
Ah, this issue should have been filed in the `creative-scala-template` project! @kris48k my bad, let's file this issue here https://github.com/underscoreio/creative-scala-template/issues (this is the wrong repository)

**Comment by noelwelsh** [comment]
Closing this one. My bad committing broken code.
